Repository mohitparmar1/Shopy, pull requests merged in 2024-05, with the labels that each got.

#16 Fixed vercel redirects
  vercel.json
Labels: GSSOC'24, Easy

#44 Fix Issue #20: [BUG] Fixing the broken social links
  src/Components/Footer.jsx
Labels: GSSOC'24, Easy

#56 fixed issue #37
  src/Components/Hero.jsx
Labels: GSSOC'24, Easy

#69 fixed issue #36
  src/Pages/Login.jsx
  src/Pages/Signup.jsx
  src/assets/google.png
Labels: GSSOC'24, Easy

#65 RESTful API for Items - fixes #19
  server/.gitignore
  server/config/DBconnect.js
  server/controllers/kids-controller.js
  server/controllers/mens-controller.js
  server/controllers/womens-controller.js
  server/index.js
  server/models/Kids-model.js
  server/models/Mens-model.js
  server/models/Womens-model.js
  server/package.json
  server/routes/kids-route.js
  server/routes/mens-route.js
  server/routes/womens-route.js
Labels: GSSOC'24, Hard

#80 Fixed : Make Selected Size Active #79
  src/Components/ProductDisplay.jsx
Labels: GSSOC'24, Easy

#78 Horizontal Scrollbar fixed
  src/Pages/Shop.jsx
Labels: GSSOC'24, Easy

#81 [Feat]: add ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, GSSOC'24, Easy

#170 reDesign a category header
  package-lock.json
  package.json
  src/Components/Breadcrumb.jsx
Labels: GSSOC'24, Level 2

#161 fix: add config.env.sample file
  server/config.env.sample
  server/index.js
Labels: GSSOC'24, Level 1

#192 Cart UI
  src/Components/CartItems.jsx
  src/index.css
Labels: GSSOC'24, Level 2

#203 Create CONTRIBUITING.md
  CONTRIBUITING.md
Labels: GSSOC'24, Level 2

#216 Feat: Added dark mode to home page.
  package-lock.json
  package.json
  src/App.jsx
  src/Components/DarkModeToggle.jsx
  src/Components/Hero.jsx
  src/Components/Item.jsx
  src/Components/Navbar.jsx
  src/Components/Newsletter.jsx
  src/Components/Offers.jsx
  src/Components/Popular.jsx
  tailwind.config.js
Labels: GSSOC'24, Level 2

#187 Fixes: #83 Login and Signup form validation fixed
  config.env
  server/.gitignore
  server/config/DBconnect.js
  server/index.js
  src/Pages/Login.jsx
  src/Pages/Signup.jsx
Labels: GSSOC'24, Level 2

#130 Add contact page
  src/App.jsx
  src/Components/Footer.jsx
  src/Components/Navbar.jsx
  src/Pages/Contact.jsx
  src/assets/chat_icon.png
  src/assets/email_icon.png
  src/assets/phone_icon.png
Labels: GSSOC'24, Level 1

#185 Add wishlist button in the product card (fixes #134)
  src/Components/Item.jsx
  src/Components/Popular.jsx
  src/Context/SavedContext.jsx
  src/assets/filled_wishlist.png
  src/assets/outlined_wishlist.png
Labels: GSSOC'24, Level 2

#219 Auto commenting feature added for merged prs
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: GSSOC'24, Level 1
