Repository mohitparmar1/Shopy, pull requests merged in 2024-06, with the labels that each got.

#233 [Fixes]: Corrected the UI and Navbar and Horizontal problems
  package-lock.json
  src/Components/DarkModeToggle.jsx
  src/Components/Navbar.jsx
  src/Components/Newsletter.jsx
Labels: Level 2, gssoc

#231 Empty cart message added
  src/Components/CartItems.jsx
  src/assets/Empty_Cart_img.png
Labels: Level 1, gssoc

#228 Add search products functionality (fixes #136)
  src/App.jsx
  src/Components/Navbar.jsx
  src/Pages/Search.jsx
Labels: Level 2, gssoc

#253 Adding a Preloader
  .vscode/settings.json
  index.html
Labels: level2, gssoc

#256 PR:#235 Added Payment.jsx & fixed styling issues in cart
  src/App.jsx
  src/Components/CartItems.jsx
  src/Components/Payment.jsx
  src/Pages/PaymentSucces.jsx
Labels: level2, gssoc

#245 added wishlist empty message wrapper (fixed #133)
  src/Components/SavedItems.jsx
Labels: level1, gssoc
